"""initial

Revision ID: 6c0a86b76e27
Revises: 
Create Date: 2025-04-15 17:31:01.036732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c0a86b76e27'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('xp', sa.Integer(), nullable=False),
    sa.Column('avatar_url', sa.String(length=255), nullable=False),
    sa.Column('objetivo', sa.String(length=255), nullable=False),
    sa.Column('mood', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('logro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=120), nullable=False),
    sa.Column('descripcion', sa.String(length=500), nullable=False),
    sa.Column('unlocked_at', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mision',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=120), nullable=False),
    sa.Column('descripcion', sa.String(length=500), nullable=False),
    sa.Column('categoria', sa.String(length=100), nullable=False),
    sa.Column('xp_reward', sa.Integer(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('current_xp', sa.Integer(), nullable=False),
    sa.Column('total_xp', sa.Integer(), nullable=False),
    sa.Column('missions_completed', sa.Integer(), nullable=False),
    sa.Column('time_spent', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('logro_stat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('logro_id', sa.Integer(), nullable=False),
    sa.Column('stat_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['logro_id'], ['logro.id'], ),
    sa.ForeignKeyConstraint(['stat_id'], ['stat.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mision_logro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mision_id', sa.Integer(), nullable=False),
    sa.Column('logro_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['logro_id'], ['logro.id'], ),
    sa.ForeignKeyConstraint(['mision_id'], ['mision.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mision_stat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mision_id', sa.Integer(), nullable=False),
    sa.Column('stat_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['mision_id'], ['mision.id'], ),
    sa.ForeignKeyConstraint(['stat_id'], ['stat.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mision_stat')
    op.drop_table('mision_logro')
    op.drop_table('logro_stat')
    op.drop_table('stat')
    op.drop_table('mision')
    op.drop_table('logro')
    op.drop_table('user')
    # ### end Alembic commands ###
